language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34

install:
 - pip install -q tox coveralls

script:
  - tox

after_success:
  - coveralls

notifications:
  email:
    - maze@pyth0n.org
